app_name: app1
aws_region: eu-west-1
modules_to_deploy:
  - database
  - cache

modules_to_deploy:
  - database
  - cache

reuse_infrastructure:
  networking: true
  security_groups: true
  kms: true
  database: false
  cache: false
  eks: true
  messaging: true

networking:
  vpc_name_tag: "infra-mgmt-vpc"

database:
  db_allocated_storage: 20
  db_instance_class: db.t3.micro
  db_engine_version: "15.4"
  db_name: app1_db
  db_multi_az: false
  db_availability_zone: us-west-2b
  db_credentials_secret_name: rds-app1-credentials

cache:
  cache_node_type: cache.t3.medium
  engine_version: "7.1"
  num_cache_nodes: 1
  cache_cluster_id: app1-cache-cluster