app_name: infra_mgmt
modules_to_deploy: ["networking", "eks", "security_groups", "kms"] # Deploy Networking and EKS and Security Groups and KMS

aws_region: eu-west-1

reuse_infrastructure:
  networking: false # Indicate CREATE new networking
  eks: false        # Indicate CREATE new EKS

networking: # Configuration for NEW networking
  vpc_cidr: "10.0.0.0/16"
  public_subnet_cidrs: ["10.0.1.0/24", "10.0.2.0/24"]
  private_subnet_cidrs: ["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]
  azs: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]

eks: # Configuration for NEW EKS
  cluster_name: "shared-eks-cluster-name"

kms:
  key_prefix: shared-infra-encryption
  deletion_window_in_days: 10