app_name: infra_mgmt
modules_to_deploy:
  - networking
  - security_groups
  - kms
  - eks

aws_region: eu-west-1

reuse_infrastructure:
  networking: false
  security_groups: false
  kms: false
  database: false
  cache: false
  eks: false
  messaging: false

networking:
  vpc_cidr: "10.0.0.0/16"
  public_subnet_cidrs: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  private_subnet_cidrs: ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
  vpc_name_tag: "infra-mgmt-vpc"

kms:
  key_prefix: infra-mgmt-kms

eks:
  cluster_name: infra-mgmt-eks-cluster